### ISSUE TITLE
use trie for route matching

### ISSUE THREAD

**Issue by gernest** [pdf/vectyx#1]
Hey, awesome library. I was wondering if you might be interested with a trie implementation for matching routes. I have experience with this, and it is fast and more efficient  [my go router](https://github.com/gernest/alien) has a neat implementation.

I can take a stab on this if you think it might be worth it. trie structures are very good for routing.

**Comment by pdf** [comment]
This project is really just for experimentation, I should probably add a big note to the README(s) to that effect.

Once some of the blockers are worked out on the main vecty project, I'll take another good look at this - I don't doubt that matching performance could be improved with radix or the like, but this was more about a first pass at what's possible, and what sort of usage pattern maps well to a tree of nested components.

**Comment by gernest** [comment]
Thanks for the feedback. I'm closing this  issue for now.
